services:
  #frontend:
  #backend:
  database:
    image: postgres:latest
    container_name: fieldnotes_db
    restart: always
    networks:
      - blog_net
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    #logging:
      #driver: syslog
      #options:
        #syslog-address: "udp://127.0.0.1:514"
        #tag: "fieldnotes-db"
  migrate:
    image: migrate/migrate:latest
    container_name: fieldnotes_db_migrate
    restart: no
    networks:
      - blog_net
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    command: ["-path", "/migrations", "-database",  "${DB}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations

networks:
  blog_net:
    driver: bridge

volumes:
  postgres_data: